---
ID: "a4e5792b-f37a-4b62-a4b1-9bebd0dd4937"
Parent: "f6d51398-807d-4df4-a738-6044874e61ca"
Template: "f6d51398-807d-4df4-a738-6044874e61ca"
Path: /sitecore/templates/Feature/Basic Content/Data Source/Perk/Perks Section/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210816T121958Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fb9a752a-cdff-4ff8-ae1b-7c4f3d3db76c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210820T111632Z
