---
ID: "2f2ef9d0-b44e-4738-9953-c565fa0dc367"
Parent: "098f9271-a7a5-4e37-9e8e-97b3f13418bf"
Template: "098f9271-a7a5-4e37-9e8e-97b3f13418bf"
Path: /sitecore/templates/Feature/Basic Content/Data Source/Base/_Slider/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210816T115129Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0d9463a7-42b9-4662-addf-8803dc27f91b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210816T115137Z
