---
ID: "eae5ac18-a9b6-4af2-9175-af2782d16db2"
Parent: "f956bde2-d768-4226-8d3c-10c5ab608580"
Template: "f956bde2-d768-4226-8d3c-10c5ab608580"
Path: /sitecore/templates/Feature/Basic Content/Data Source/Slider/Year Slide Item/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210825T115207Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "80b80c93-1dd3-49ee-bb46-346955a4622a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210825T120220Z
