---
ID: "dd405cec-a000-49aa-b690-c9031903e47c"
Parent: "b62c98f1-67bd-4c1f-bb69-6606ca219b31"
Template: "b62c98f1-67bd-4c1f-bb69-6606ca219b31"
Path: /sitecore/templates/Project/Hackathon/Page Types/Service Detail Page/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210924T070911Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3ae77cb7-55c4-4f66-a604-b3c9434e4c8c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210924T070911Z
