---
ID: "a64afc94-fc3f-416a-a531-71e86668d305"
Parent: "9edfb03d-248c-4e26-a9c9-e63e2d107fe3"
Template: "9edfb03d-248c-4e26-a9c9-e63e2d107fe3"
Path: /sitecore/templates/Feature/Hero/Data Source/Hero Section Media/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210826T084601Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f24cafb7-52dc-4001-b84e-3c8dcc1dbe71"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210826T084601Z
