---
ID: "c9eb1fdc-f923-451f-95eb-c700db8825e3"
Parent: "01994733-ebc1-41e2-bd5b-43c3ed4d1740"
Template: "01994733-ebc1-41e2-bd5b-43c3ed4d1740"
Path: /sitecore/templates/Feature/Team/Data Source/Team Section/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210908T081151Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "31ad3fc6-44b9-4d46-9a92-4c97a91552b4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210908T082503Z
