---
ID: "5a3e52a8-35f7-4a78-8242-8ddeb068cdd5"
Parent: "daf9e1fa-ecdf-4756-9460-caa2d11be9ee"
Template: "daf9e1fa-ecdf-4756-9460-caa2d11be9ee"
Path: /sitecore/templates/Feature/Basic Content/Data Source/Logo/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210825T081944Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f2e16f95-482a-4649-b897-1db7541cba57"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210825T082837Z
