---
ID: "bb53e1d5-37c5-4773-b833-2cd1ac92ca90"
Parent: "2fae4e28-0154-4d1d-8bb1-7854ded7101e"
Template: "2fae4e28-0154-4d1d-8bb1-7854ded7101e"
Path: /sitecore/templates/Project/Hackathon/Page Types/Blog Keyword Page/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210908T090251Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "cb9c7122-d4f1-4ecf-8453-6db9156597b8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210908T090251Z
