---
ID: "b88ba611-e488-47e3-bec5-278c8c1464f8"
Parent: "9e0eb1da-e8d0-472d-afba-4f1794d57d02"
Template: "9e0eb1da-e8d0-472d-afba-4f1794d57d02"
Path: /sitecore/templates/Feature/Basic Content/Data Source/Slider/Instagram Slider/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210816T114925Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7532df06-5944-459c-8211-feac3f4fcecd"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210816T114925Z
