---
ID: "7e3343aa-f583-428e-86d0-40f1ab641abd"
Parent: "2adeb5fb-b6ce-4d99-af5f-c99caa865abe"
Template: "2adeb5fb-b6ce-4d99-af5f-c99caa865abe"
Path: /sitecore/templates/Feature/Service/Data Source/_Service/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210924T093549Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fc779e5c-dff6-422b-b5fc-f79072b4ee44"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210924T093549Z
