---
ID: "c38e4b2a-8075-471a-8a6e-fa31d02dd58a"
Parent: "f1eb0533-057a-455e-aa18-22eec4a75505"
Template: "f1eb0533-057a-455e-aa18-22eec4a75505"
Path: /sitecore/templates/Feature/Basic Content/Data Source/FAQ/FAQ Item/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210816T125007Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e21a13ac-a4fb-455e-9115-c003a943ab52"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "cd7bc676-b1d5-4524-ba58-9460c23c17a9"
      Hint: Question
      Value: $name
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210910T065300Z
