---
ID: "d47e4b45-bb1f-44f3-888a-53a27ab78ab9"
Parent: "f2bd5a96-d661-4080-9950-cb6a916dfc06"
Template: "f2bd5a96-d661-4080-9950-cb6a916dfc06"
Path: /sitecore/templates/Feature/Basic Content/Data Source/Error Details/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210825T063803Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "886c5fd0-0e1a-4111-a4eb-1b50729444fa"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210825T063900Z
