---
ID: "1cd37066-d11b-4bce-8811-2a107ca280d0"
Parent: "d11575b6-2d4f-41ed-a2c9-fd3fb64c4e46"
Template: "d11575b6-2d4f-41ed-a2c9-fd3fb64c4e46"
Path: /sitecore/templates/Feature/Blog/Data Source/Techtalk/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210816T102223Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c537f2d4-4850-4307-8563-60ce7e2a5d73"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210816T102223Z
