---
ID: "58a50bc8-ae54-4ea6-929f-72fc4fc41a96"
Parent: "b9c9a7eb-8ea7-4462-9053-176ec6d50d8d"
Template: "b9c9a7eb-8ea7-4462-9053-176ec6d50d8d"
Path: /sitecore/templates/Feature/Career/Data Source/Open Jobs/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210816T101759Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "120b7351-0a6d-4dc1-a40d-f6c6bb746b1a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210816T101759Z
