---
ID: "0efbd534-667d-483d-a9e2-f20c4e470857"
Parent: "9d247ce7-d2c0-48e4-a577-ad55d8d4ba33"
Template: "9d247ce7-d2c0-48e4-a577-ad55d8d4ba33"
Path: /sitecore/templates/Feature/Career/Data Source/Location/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0a8f0231-f33a-451e-94be-b1cce9c1f28e"
      Hint: Title
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210831T084217Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "76dc86b1-e4ee-4b71-a13c-74a32fa47599"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210917T112604Z
