---
ID: "20140106-c26d-4c44-823c-0eccf3599ff5"
Parent: "451d5ae1-d3a2-42ce-9cb0-aae7ebed5a9f"
Template: "451d5ae1-d3a2-42ce-9cb0-aae7ebed5a9f"
Path: /sitecore/templates/Feature/Basic Content/Data Folders/FAQs Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{F1EB0533-057A-455E-AA18-22EEC4A75505}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210816T125112Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5dfceb4e-0f00-4fd2-b7a3-f17e24540910"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210922T152332Z
