---
ID: "54693ad2-dc54-45e2-8e0e-f1435e958142"
Parent: "87f6ad54-e852-4fab-8ac0-d229d6a225f2"
Template: "87f6ad54-e852-4fab-8ac0-d229d6a225f2"
Path: /sitecore/templates/Feature/Basic Content/Data Source/Slider/Media Slider Item/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210816T122421Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5126a0e0-a867-438d-a1e7-425a079186eb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210816T122421Z
