---
ID: "141a87cb-0626-442f-99fa-6b2f2dce4501"
Parent: "12547079-661c-4a1b-a9d8-eb4d65ed1095"
Template: "12547079-661c-4a1b-a9d8-eb4d65ed1095"
Path: /sitecore/templates/Feature/Basic Content/Data Source/Standard Text Module/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210901T085011Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2b66d8aa-9124-464f-9122-df06f5a665fa"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210901T085011Z
